spring:
  application:
    name: emias
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
  analysis:
    queue-send-name: analysis-send-queue
  duration:
    saving: 15
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8082