spring:
  application:
    name: emias
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
    user: ${ACTIVEMQ_USER:admin}
    password: ${ACTIVEMQ_PASSWORD:admin}
    packages:
      trust-all: true
  analysis:
    queue-send-name: analysis-send-queue
  duration:
    saving: 15
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
server:
  port: 8082