spring:
  application:
    name: analysis
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME:mongodb}:${MONGO_PASSWORD:password}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:analysis}?authSource=${MONGO_AUTH_DB:admin}
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
    user: admin
    password: admin
    packages:
      trust-all: true
  analysis:
    queue-send-name: analysis-send-queue
    notification-queue-name: MQ_QUEUE
emias:
  url: ${EMIAS_URL:http://localhost:8081}
jwt:
  secret: 8fd35ee52eeae928ad871e7ce5a4cb5fe73cab6dd03922929bddd844aaf5a0d7
server:
  port: 8081
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
  show-actuator: false